#!/usr/bin/env python3


import sys
from mysql.connector import connect


class dataModel:

    def __init__(self):

        self.option = {

            'dataQualityLevel': ['low', 'high', 'ref'],

            'libMethod': ['iDrop', '10x'],
            'seqMethod': ['full-length', '3-terminal'],

        }

        self.sampleObj = {

            'identity': '',

            'species': '',
            'age': '',
            'tissue': '',

        }

        self.dataModel = {

            'identity': '',
            'alias': [],

            # Append sample object here
            'usedSample': [],

            'libMethod': '',
            'seqMethod': '',

            'totalCellNumber': 0,
            'clusterNumber': 0,

            'cellNumberInEachCluster': [],
            'markerGeneInEachCluster': [[]],

            'totalExpSpan': [0, 0],
            'expSpanInEachCluster': [[]],

            'dataQualityLevel': '',

        }

        self.dbObj = connect(

            host='localhost',
            user='cornflower',
            passwd='$th00516',
            database='cornflower',

        )

    @staticmethod
    def autoGenerateSampleIdentity():
        """"""

        pass

    @staticmethod
    def autoGenerateDataIdentity():
        """"""

        pass

    def parseInputFile(self, sampleFiles):
        """"""

        for sampleFile in sampleFiles:

            pass

    def exportDataToDB(self):
        """"""

        dbCursor = self.dbObj.cursor()

    def manageDB(self):
        """"""

        dbAdminCursor = self.dbObj.cursor()
